### ISSUE TITLE
脚本api请求错误

### ISSUE THREAD

**Issue by cutemoe** [zfb132/qcloud-ssl-cdn#17]
以下是报错
[TencentCloudSDKException] code:ClientNetworkError message:HTTPSConnectionPool(host='ssl.tencentcloudapi.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f789475f080>: Failed to resolve 'ssl.tencentcloudapi.com' ([Errno -3] Try again)")) requestId:None
获取新证书id失败

应该是腾讯云请求api需要加时间戳了，请作者更新一下脚本，谢谢。很喜欢用这个脚本，真的很省心！

**Comment by zfb132** [comment]
> [TencentCloudSDKException] code:ClientNetworkError message:HTTPSConnectionPool(host='ssl.tencentcloudapi.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f789475f080>: Failed to resolve 'ssl.tencentcloudapi.com' ([Errno -3] Try again)")) requestId:None

根据你的报错信息来看，问题是你的机器解析域名`ssl.tencentcloudapi.com`失败，建议你先核实一下这个问题  
[腾讯云文档-SSL-上传证书](https://cloud.tencent.com/document/api/400/41665#2.-.E8.BE.93.E5.85.A5.E5.8F.82.E6.95.B0)：时间戳属于公共参数，每次请求都会带上（`tencentcloud-sdk-python`内置该功能）

> 应该是腾讯云请求api需要加时间戳了

我猜测你可能是在浏览器或命令行直接访问了 [ssl.tencentcloudapi.com](https://ssl.tencentcloudapi.com/)

**Comment by cutemoe** [comment]
换成了国外服务器就可以了，真的很离谱。我用国内的腾讯云ping这个域名也是正常的，就是一直报这个错。怀疑是腾讯云自己搞鬼。谢谢作者大大的回复！
