### ISSUE TITLE
在Docker环境中，由于目标证书文件夹中存在历史证书，新申请的证书无法覆盖，导致上传时仍使用旧证书的问题。

### ISSUE THREAD

**Issue by a12110** [zfb132/qcloud-ssl-cdn#20]
在使用过程中，我发现 Docker 版本的自动更新证书功能无法正确更新 CDN 中的证书信息，总是上传上一次申请的旧证书。经过排查，发现问题出在生成证书文件夹时的复制逻辑。

在原 `update.sh` 脚本的第 10 行：

```bash
cp -r ${CERT_HOME}/${ACME_DOMAIN}_ecc ${CERT_HOME}/${ACME_DOMAIN}
```

如果目标文件夹 `${CERT_HOME}/${ACME_DOMAIN}` 中存在上一次申请的旧证书，且旧证书文件名与新证书文件名相同，则会导致复制操作失败，从而无法正确更新证书。

为了解决这一问题，我将上述命令修改为：

```bash
cp -rf ${CERT_HOME}/${ACME_DOMAIN}_ecc ${CERT_HOME}/${ACME_DOMAIN}
```

此修改确保新证书能够强制覆盖旧证书，问题已得到解决。我已提交合并请求 #19，恳请作者将此更改合并至主分支，并构建一个新版本的 Docker 镜像。

**Comment by zfb132** [comment]
谢谢你的PR，很有用
