### ISSUE TITLE
cdn刷新为啥只刷新国内呢

### ISSUE THREAD

**Issue by monlor** [zfb132/qcloud-ssl-cdn#5]

**Comment by zfb132** [comment]
这是我的个人需求  
https://github.com/zfb132/qcloud-ssl-cdn/blob/41f1f0f36925b0b16c4d8ef41ddc6f06b6f6477b/main.py#L113  
因为我的源站是面向国外的，所以对于国外用户的访问不需要用到CDN，也就不需要CDN刷新

**Comment by monlor** [comment]
刷新位置可以添加参数控制么，我觉得这个项目非常好，我准备制作一个Docker镜像来使用，更方便
还有关于sitemap，是否也可以加个参数控制，因为可能有的博客没有sitemap

**Comment by zfb132** [comment]
可以，非常欢迎提交PR

**Comment by monlor** [comment]
> 刷新区域 无此参数时，默认刷新加速域名所在加速区域 填充 mainland 时，仅刷新中国境内加速节点上缓存内容 填充 overseas 时，仅刷新中国境外加速节点上缓存内容 指定刷新区域时，需要与域名加速区域匹配

我看了下官方介绍，这个选项是不是没有必要，不填默认刷新你配置的加速区域

**Comment by zfb132** [comment]
是的，我小修一下提交一版新代码

**Comment by zfb132** [comment]
@monlor 已经修改了，你可以测试一下

**Comment by monlor** [comment]
好的👌

**Comment by zfb132** [comment]
@monlor 试试这一版？  
https://github.com/zfb132/qcloud-ssl-cdn/commit/09f79d4e54e7d601282913ddcab14ec5c26b4a56

**Comment by monlor** [comment]
ok 👍

**Comment by monlor** [comment]
https://github.com/zfb132/qcloud-ssl-cdn/blob/09f79d4e54e7d601282913ddcab14ec5c26b4a56/main.py#L59
这里的删除证书会有个问题，如果我的域名申请了腾讯云的证书删除会报错，可否只删除From=Upload的证书

**Comment by monlor** [comment]
奇怪，我刚删除报错了，第二次成功了
<img width="803" alt="image" src="https://user-images.githubusercontent.com/20394007/164259679-5ecb4c48-ffe4-41ff-8a53-770165c5b98d.png">

**Comment by monlor** [comment]
刷新url的接口增加下这个参数吧，如果url中包含中文会报错
<img width="381" alt="image" src="https://user-images.githubusercontent.com/20394007/164260242-55dc4d07-ddc3-4cfb-bf5c-dd53757a1152.png">

**Comment by monlor** [comment]
我的预热没有识别出来url，刷新识别出来，只是执行刷新的时候报错，我瞅瞅

获取指定cdn基本信息成功
获取CDN预热配额和每日可用量信息成功
成功预热0个URL
实例化cdn client成功
获取指定cdn基本信息成功
获取CDN刷新URL配额和每日可用量信息成功

**Comment by zfb132** [comment]
> https://github.com/zfb132/qcloud-ssl-cdn/blob/09f79d4e54e7d601282913ddcab14ec5c26b4a56/main.py#L59
> 
> 
> 这里的删除证书会有个问题，如果我的域名申请了腾讯云的证书删除会报错，可否只删除From=Upload的证书

第一次与第二次运行的结果为什么不同，这个问题我也没办法测试  

> 刷新url的接口增加下这个参数吧，如果url中包含中文会报错

我明天给它加一下

> 我的预热没有识别出来url，刷新识别出来，只是执行刷新的时候报错

这个预热和刷新功能我是在自己的CDN加速域名测试成功后才更新的代码(唯一的区别我的那个是`国内加速`)，所以这个问题可能需要麻烦你在自己那里调试解决

**Comment by monlor** [comment]
预热的问题时这里没有加global的判断逻辑：
https://github.com/zfb132/qcloud-ssl-cdn/blob/09f79d4e54e7d601282913ddcab14ec5c26b4a56/main.py#L111
```python
if cdn_region == 'global':
    cdn_region = ['mainland', 'overseas']
else:
    cdn_region = [cdn_region]
```

**Comment by zfb132** [comment]
> 预热的问题时这里没有加global的判断逻辑：
> 
> https://github.com/zfb132/qcloud-ssl-cdn/blob/09f79d4e54e7d601282913ddcab14ec5c26b4a56/main.py#L111
> 
> ```python
> if cdn_region == 'global':
>     cdn_region = ['mainland', 'overseas']
> else:
>     cdn_region = [cdn_region]
> ```

确实忘了给预热功能更新代码了
