### ISSUE TITLE
上传的证书内容不符合CA证书的标准格式，请您核对证书类型是否有误 

### ISSUE THREAD

**Issue by peihuanhuan** [zfb132/qcloud-ssl-cdn#8]
```
实例化一个ssl_client成功
获取ssl证书列表成功
[TencentCloudSDKException] code:FailedOperation.CertificateCaError message:温馨提示：上传的证书内容不符合CA证书的标准格式，请您核对证书类型是否有误 requestId:6eb75f10-6f8d-4c80-abe7
获取新证书id失败
```

你好，上传证书的时候报错，但把生成的证书在控制台里直接上传是能 work 的

**Comment by miaomiaocatmsg** [comment]
[TencentCloudSDKException] code:FailedOperation.CdnConfigError message:域名加速服务已关闭，请先前往域名管理启动域名 requestId:fe6a1fd7-e801-4da6-90d8-71690ead18c7
为CDN设置SSL证书Eq4hcD10出错

离谱 0 0

**Comment by Nekotora** [comment]
也遇到了相同的问题，我的解决方式是，
在main.py的17行，将 `"type": "CA"` 修改为 `"type": "SVR"` 就正常了，
看起来证书类型写错了，签发出来的证书确实是SVR不是CA，
不知道和 acme.sh 前段时间改用 zeroSSL 作为默认证书提供商有没有什么关系。
相关文档：https://cloud.tencent.com/document/product/400/41665

I encountered the same issue. 
My solution was to change `"type": "CA"` to `"type": "SVR"` on line 17 of main.py, and then everything worked fine. 
It looks like the certificate type was incorrectly specified; the issued certificate is indeed SVR, not CA.
I'm not sure if this is related to acme.sh switching to ZeroSSL.
Relevant documentation: https://cloud.tencent.com/document/product/400/41665

**Comment by zfb132** [comment]
https://github.com/zfb132/qcloud-ssl-cdn/blob/846df23a2f7b60720f712c3c848ecdd6d7ceb037/main.py#L5-L16

@Nekotora 在使用前注意拉取最新代码，此问题应该在2023-12-01已被修复

[Fix "code:InvalidParameter.WithCaAttr" error.](https://github.com/zfb132/qcloud-ssl-cdn/commit/9408c504fbae2e2e85e44f83f0bb73de64273c23)

**Comment by Nekotora** [comment]
> @Nekotora 在使用前注意拉取最新代码，此问题应该在2023-12-01已被修复
> 
> [Fix "code:InvalidParameter.WithCaAttr" error.](https://github.com/zfb132/qcloud-ssl-cdn/commit/9408c504fbae2e2e85e44f83f0bb73de64273c23)

😮啊抱歉，我一直在使用一个很久之前fork下来的旧版本，
最近部署新的时候才发现问题，原来已经修掉了，
非常方便的工具，感谢！
